### PR TITLE
Testing Windows and Python 3.5

### PR DESCRIPTION
**Pull request by ocefpaf**
Just checking what is the error we get when building on Windows with Python 3.5.

### CODE REVIEW

**Comment by ocefpaf** [comment]
``` shell
C:\conda\conda-bld\work\spatialindex-src-1.8.5\src\spatialindex\LineSegment.cc(488): warning C4273: 'SpatialIndex::operator <<': inconsistent dll linkage 
c:\conda\conda-bld\work\spatialindex-src-1.8.5\include\spatialindex\LineSegment.h(86): note: see previous definition of '<<' 
NMAKE : fatal error U1077: 'C:\PROGRA~2\MI0E91~1.0\VC\bin\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
Command failed: C:\Windows\system32\cmd.exe /c call bld.bat
Command exited with code 1
```

**Comment by ocefpaf** [comment]
@gillins if you have some free time and evaluate if fixing the Python 3.5 build in Windows is a low hanging fruit or a a difficult task?

**Comment by gillins** [comment]
Yes I should be able to look at this soon. I'll report back.

**Comment by gillins** [comment]
Attached are a couple of patches. Not sure if they may be needed for all Windows builds.

Seems there is some work on their github to support VS2015 formerly for the next release so maybe worth making a note to upgrade when it is ready.

[cmakelists.patch.txt](https://github.com/conda-forge/libspatialindex-feedstock/files/211102/cmakelists.patch.txt)
[tool.h.patch.txt](https://github.com/conda-forge/libspatialindex-feedstock/files/211103/tool.h.patch.txt)

**Comment by ocefpaf** [comment]
> Attached are a couple of patches. Not sure if they may be needed for all Windows builds.

Awesome! Thanks!!

> Seems there is some work on their github to support VS2015 formerly for the next release so maybe worth making a note to upgrade when it is ready.

I will take a look!

@gillins I am writing a blog piece about conda-forge and I would like to mention your efforts to make Windows a first class citizen. If you are OK with this and if you find some time can you e-mail (my e-mail is in my GitHub profile) me a tiny bio (name, interest in conda-forge, how you use it...).

**Comment by ocefpaf** [comment]
And we have green! Thanks @gillins!!

**Pull request merged**
